server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://www.eureka-server.com:8080/eureka,http://www.eureka-server2.com:8082/eureka
    register-with-eureka: false
    fetch-registry: false
spring:
  application:
    name: eureka-server
